name: Assignment Helper

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  issues: write

jobs:
  reply-to-assignment-request:
    name: Reply To Assignment Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm ci

      - name: Reply
        run: npm run issue:assignment-helper
        env:
          MAINTAINER_TOKEN: ${{ secrets.MAINTAINER_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
